server:
  port: 8082

app:
  create-default-entities: false  # сброс БД и создание сущностей для примера

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/objects
    username: postgres
    password: postgres
  driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: statistics-group
      auto-offset-reset: earliest

  data:
    mongodb:
      host: localhost
      port: 27017
      database: events_store
      username: root
      password: root
      authentication-database: admin
#      uri: mongodb://localhost:27017/events_store
      connection-timeout: 5000 # Тайм-аут в миллисекундах


