version: '3'
services:
  postgres:
    image: postgres:12.3
    container_name: objects-app
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "objects"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  mongodb:
    image: mongo:6.0.8
    container_name: mongo-events-store
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: events_store


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1



